# WARNING
# This is script is wrong, I write it only for testing Travis.

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pyside python-matplotlib

script: python main.py
